name: Deploy B2CID worker to Cloudflare
# Workflow to deploy the B2CID worker to Cloudflare Workers
# This ensures that the worker is deployed to https://b2cid.daokotube.workers.dev
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ⚙️
    environment:
      name: cloudflare-worker
      url: https://b2cid.daokotube.workers.dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: cloudflare-worker
          initial-status: in_progress
          description: "Deploying B2CID worker to Cloudflare"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Publish to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_WRKR_TOKEN }}
          command: deploy

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          environment-url: https://b2cid.daokotube.workers.dev
          description: "Deployment successful"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          description: "Deployment failed"